language: julia

os:
  - linux
  - osx

julia:
  - 1.3
  - nightly

matrix:
  allow_failures:
    - os: osx
    - julia: nightly
  
notifications:
  email: true

script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - cd $HOME; if [[ ! -d cmdstan ]]; then git clone https://github.com/stan-dev/cmdstan.git; fi
  - cd $HOME/cmdstan; git checkout v2.18.0; make stan-update; make build
  - export CMDSTAN_HOME=$HOME/cmdstan
  - cd $TRAVIS_BUILD_DIR
  - julia -e 'using Pkg; Pkg.test("Stan"; coverage=true)'
  
branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
    
notifications:
  email: false
  
git:
  depth: 99999999
